### ISSUE TITLE
Correct broken links in README.md

### ISSUE THREAD

**Issue by nickdex** [nickdex/PasteIt-Android#1]
### First Timers Only :new: :hatched_chick: 
This issue is reserved for people who never contributed to Open Source before. We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you :gift_heart: [About First Timers Only](http://www.firsttimersonly.com/)

### What you will need to know :thinking:
Nothing. This issue is meant to welcome you to Open Source :blush: I am happy to walk you through the process

### Step by Step :clipboard:

- [ ] :raising_hand_woman: **Claim this issue:** Comment below
- [ ] :fork_and_knife: **Fork the repository** to have your own copy of this repository by clicking the fork button
- [ ] :arrow_down: **Clone the fork** in your machine and **make a separate branch**. Its a good practice to name the branch something like `fix/xxx` or `feature/xxx` where `xxx` is a short description of the changes or feature you are attempting to add
 `$ git clone https://github.com/yourUsername/PasteIt-Android.git`
 `$ git checkout -b [name_of_your_new_branch]`
- [ ] :memo: **Fix LIBRARIES.md and LICENSE.md links in README.md:**
Replace username by nickdex and appname by PasteIt-Android in
`[LIBRARIES](https://github.com/username/appname/blob/master/LIBRARIES.md)` and
`[LICENSE](https://github.com/username/appname/blob/master/LICENSE.md)`
- [ ] :ballot_box_with_check: **Check if the links are working:** They should open these two files -
[LIBRARIES](https://github.com/nickdex/PasteIt-Android/blob/master/LIBRARIES.md) and [LICENSE](https://github.com/nickdex/PasteIt-Android/blob/master/LICENSE.md)
- [ ] :floppy_disk: **Commit** your changes with message `Fix #1 Broken links in README.md`
- [ ] :arrow_up: **Push the changes** to Github:
 `$ git push origin [name_of_your_new_branch]`
- [ ] :twisted_rightwards_arrows: **Start a Pull Request** Set the title to `Broken links in README.md` and set description to `fix nickdex/PasteIt-Android#1`. There are two ways how you can start a pull request:
  i. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
  ii. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)
- [ ] :checkered_flag: Done :+1: Ask in comments for a review :)

**Comment by italo-batista** [comment]
Hi, Nikhil! Thanks for the opportunity! My first time ;) I did as you described at the issue. Please review the pull request!

**Comment by zdamien** [comment]
Likewise. :)

**Comment by nickdex** [comment]
@italo-batista @zdamien Both of you did good work, since it was a simple issue, I accepted both your PRs but usually the better solution is accepted (or whichever was submitted earlier). Since I'm traveling I couldn't reply earlier, sorry about that. 
I'll be back in sometime in next week and will add some more beginner friendly issues. Check them out if you are interested.
